// <auto-generated />
using System;
using DorucovaciSluzba.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DorucovaciSluzba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125185442_VsePredelanoNaIdentity")]
    partial class VsePredelanoNaIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.StavZasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StavZasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Stav = "Objednávka vytvořena"
                        },
                        new
                        {
                            Id = 2,
                            Stav = "Zásilka je v přepravě"
                        },
                        new
                        {
                            Id = 3,
                            Stav = "Doručeno"
                        },
                        new
                        {
                            Id = 4,
                            Stav = "Reklamováno"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumOdeslani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DatumOdeslani"));

                    b.Property<string>("DestinaceCP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceMesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinacePsc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceUlice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KuryrId")
                        .HasColumnType("int");

                    b.Property<int>("OdesilatelId")
                        .HasColumnType("int");

                    b.Property<int>("PrijemceId")
                        .HasColumnType("int");

                    b.Property<int>("StavId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KuryrId");

                    b.HasIndex("OdesilatelId");

                    b.HasIndex("PrijemceId");

                    b.HasIndex("StavId");

                    b.HasIndex("UserId");

                    b.ToTable("Zasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = "123-45-67",
                            DatumOdeslani = new DateTime(2025, 11, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "456",
                            DestinaceMesto = "Brno",
                            DestinacePsc = "602 00",
                            DestinaceUlice = "Nádražní",
                            KuryrId = 2,
                            OdesilatelId = 5,
                            PrijemceId = 6,
                            StavId = 3
                        },
                        new
                        {
                            Id = 2,
                            Cislo = "234-56-78",
                            DatumOdeslani = new DateTime(2025, 11, 23, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "789",
                            DestinaceMesto = "Ostrava",
                            DestinacePsc = "700 30",
                            DestinaceUlice = "Zahradní",
                            KuryrId = 3,
                            OdesilatelId = 6,
                            PrijemceId = 7,
                            StavId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cislo = "345-67-89",
                            DatumOdeslani = new DateTime(2025, 11, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "321",
                            DestinaceMesto = "Plzeň",
                            DestinacePsc = "301 00",
                            DestinaceUlice = "Školní",
                            OdesilatelId = 7,
                            PrijemceId = 8,
                            StavId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = "456-78-90",
                            DatumOdeslani = new DateTime(2025, 11, 22, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "123",
                            DestinaceMesto = "Praha",
                            DestinacePsc = "110 00",
                            DestinaceUlice = "Hlavní",
                            KuryrId = 2,
                            OdesilatelId = 8,
                            PrijemceId = 5,
                            StavId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = "567-89-01",
                            DatumOdeslani = new DateTime(2025, 11, 18, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "789",
                            DestinaceMesto = "Ostrava",
                            DestinacePsc = "700 30",
                            DestinaceUlice = "Zahradní",
                            KuryrId = 3,
                            OdesilatelId = 5,
                            PrijemceId = 7,
                            StavId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = "678-90-12",
                            DatumOdeslani = new DateTime(2025, 11, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "123",
                            DestinaceMesto = "Praha",
                            DestinacePsc = "110 00",
                            DestinaceUlice = "Hlavní",
                            KuryrId = 2,
                            OdesilatelId = 6,
                            PrijemceId = 5,
                            StavId = 4
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "9cf14c2c-19e7-40d6-b744-8917505c3106",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "3ea1f7bc-4de1-5fg9-d4e8-5890e8cdb4ff",
                            Name = "Podpora",
                            NormalizedName = "PODPORA"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "be0efcde-9d0a-461d-8eb6-444b043d6660",
                            Name = "Kurýr",
                            NormalizedName = "KURYR"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "29dafca7-cd20-4cd9-a3dd-4779d7bac3ee",
                            Name = "Uživatel",
                            NormalizedName = "UZIVATEL"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CP")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatumNarozeni")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mesto")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Psc")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ulice")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b09a83ae-cfd3-4ee7-97e6-fbcf0b0fe78c",
                            Email = "admin@dorucovacisluzba.cz",
                            EmailConfirmed = true,
                            FirstName = "Jan",
                            LastName = "Novák",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@DORUCOVACISLUZBA.CZ",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEM9O98Suoh2o2JOK1ZOJScgOfQ21odn/k6EYUpGWnrbevCaBFFXrNL7JZxHNczhh/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEJEPXC646ZBNCDYSM3H5FRK5RWP2TN6",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a8d96fd-5918-441b-b800-cbafa99de97b",
                            Email = "kuryr@dorucovacisluzba.cz",
                            EmailConfirmed = true,
                            FirstName = "Petr",
                            LastName = "Svoboda",
                            LockoutEnabled = true,
                            NormalizedEmail = "KURYR@DORUCOVACISLUZBA.CZ",
                            NormalizedUserName = "KURYR",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "700 123 456",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MAJXOSATJKOEM4YFF32Y5G2XPR5OFEL6",
                            Telefon = "700 123 456",
                            TwoFactorEnabled = false,
                            UserName = "kuryr"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d20c95cg-ehg5-6gg9-d0g8-hdfhb21hg90e",
                            Email = "kuryr2@dorucovacisluzba.cz",
                            EmailConfirmed = true,
                            FirstName = "Lukáš",
                            LastName = "Černý",
                            LockoutEnabled = true,
                            NormalizedEmail = "KURYR2@DORUCOVACISLUZBA.CZ",
                            NormalizedUserName = "KURYR2",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "702 456 789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "KURYR2XC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "702 456 789",
                            TwoFactorEnabled = false,
                            UserName = "kuryr2"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c19b94bf-dgf4-5ff8-c9f7-gcfga10gf89d",
                            Email = "podpora@dorucovacisluzba.cz",
                            EmailConfirmed = true,
                            FirstName = "Marie",
                            LastName = "Dvořáková",
                            LockoutEnabled = true,
                            NormalizedEmail = "PODPORA@DORUCOVACISLUZBA.CZ",
                            NormalizedUserName = "PODPORA",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "777 888 999",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "PODPORAXC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "777 888 999",
                            TwoFactorEnabled = false,
                            UserName = "podpora"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            CP = "123",
                            ConcurrencyStamp = "e31d05dh-fih6-7hh0-e1h9-ieiic32ih01f",
                            Email = "karel.prochazka@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Karel",
                            LastName = "Procházka",
                            LockoutEnabled = true,
                            Mesto = "Praha",
                            NormalizedEmail = "KAREL.PROCHAZKA@EMAIL.CZ",
                            NormalizedUserName = "KAREL.PROCHAZKA",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "603 111 222",
                            PhoneNumberConfirmed = false,
                            Psc = "110 00",
                            SecurityStamp = "UZIV1XC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "603 111 222",
                            TwoFactorEnabled = false,
                            Ulice = "Hlavní",
                            UserName = "karel.prochazka"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            CP = "456",
                            ConcurrencyStamp = "f42e16ei-gji7-8ii1-f2i0-jfjjd43ji12g",
                            Email = "eva.malkova@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Eva",
                            LastName = "Málková",
                            LockoutEnabled = true,
                            Mesto = "Brno",
                            NormalizedEmail = "EVA.MALKOVA@EMAIL.CZ",
                            NormalizedUserName = "EVA.MALKOVA",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "604 333 444",
                            PhoneNumberConfirmed = false,
                            Psc = "602 00",
                            SecurityStamp = "UZIV2XC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "604 333 444",
                            TwoFactorEnabled = false,
                            Ulice = "Nádražní",
                            UserName = "eva.malkova"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            CP = "789",
                            ConcurrencyStamp = "g53f27fj-hkj8-9jj2-g3j1-kgkkf54kj23h",
                            Email = "tomas.vesely@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Tomáš",
                            LastName = "Veselý",
                            LockoutEnabled = true,
                            Mesto = "Ostrava",
                            NormalizedEmail = "TOMAS.VESELY@EMAIL.CZ",
                            NormalizedUserName = "TOMAS.VESELY",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "605 555 666",
                            PhoneNumberConfirmed = false,
                            Psc = "700 30",
                            SecurityStamp = "UZIV3XC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "605 555 666",
                            TwoFactorEnabled = false,
                            Ulice = "Zahradní",
                            UserName = "tomas.vesely"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            CP = "321",
                            ConcurrencyStamp = "h64g38gk-ilk9-0kk3-h4k2-lhllg65lk34i",
                            Email = "jana.horakova@email.cz",
                            EmailConfirmed = true,
                            FirstName = "Jana",
                            LastName = "Horáková",
                            LockoutEnabled = true,
                            Mesto = "Plzeň",
                            NormalizedEmail = "JANA.HORAKOVA@EMAIL.CZ",
                            NormalizedUserName = "JANA.HORAKOVA",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumber = "606 777 888",
                            PhoneNumberConfirmed = false,
                            Psc = "301 00",
                            SecurityStamp = "UZIV4XC646ZBNCDYSM3H5FRK5RWP2TN6",
                            Telefon = "606 777 888",
                            TwoFactorEnabled = false,
                            Ulice = "Školní",
                            UserName = "jana.horakova"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("KuryrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("OdeslaneZasilky")
                        .HasForeignKey("OdesilatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("PrijateZasilky")
                        .HasForeignKey("PrijemceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.StavZasilka", "Stav")
                        .WithMany()
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany("DorucovaciZasilky")
                        .HasForeignKey("UserId");

                    b.Navigation("Stav");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DorucovaciSluzba.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DorucovaciSluzba.Infrastructure.Identity.User", b =>
                {
                    b.Navigation("DorucovaciZasilky");

                    b.Navigation("OdeslaneZasilky");

                    b.Navigation("PrijateZasilky");
                });
#pragma warning restore 612, 618
        }
    }
}
