// <auto-generated />
using System;
using DorucovaciSluzba.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DorucovaciSluzba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028164151_packageSeeding")]
    partial class packageSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.StavZasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StavZasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Stav = "Objednávka vytvořena"
                        },
                        new
                        {
                            Id = 2,
                            Stav = "Zásilka je v přepravě"
                        },
                        new
                        {
                            Id = 3,
                            Stav = "Doručeno"
                        },
                        new
                        {
                            Id = 4,
                            Stav = "Reklamováno"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.TypUzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TypUzivatel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Typ = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Typ = "bezny uzivatel"
                        },
                        new
                        {
                            Id = 3,
                            Typ = "kuryr"
                        },
                        new
                        {
                            Id = 4,
                            Typ = "podpora"
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DatumNarozeni")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mesto")
                        .HasColumnType("longtext");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Psc")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<int>("TypId")
                        .HasColumnType("int");

                    b.Property<string>("Ulice")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TypId");

                    b.ToTable("Uzivatel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@web.cz",
                            Heslo = "admin",
                            Jmeno = "Web",
                            Prijmeni = "Admin",
                            TypId = 1
                        },
                        new
                        {
                            Id = 2,
                            CP = "4653",
                            DatumNarozeni = new DateTime(1995, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "novak@web.cz",
                            Heslo = "test",
                            Jmeno = "Petr",
                            Mesto = "Zlín",
                            Prijmeni = "Novák",
                            Psc = "760 01",
                            Telefon = "700 600 500",
                            TypId = 2,
                            Ulice = "Kvítková"
                        },
                        new
                        {
                            Id = 3,
                            CP = "4872",
                            DatumNarozeni = new DateTime(1998, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "buben@web.cz",
                            Heslo = "test",
                            Jmeno = "Prokop",
                            Mesto = "Zlín",
                            Prijmeni = "Buben",
                            Psc = "760 01",
                            Telefon = "700 600 400",
                            TypId = 2,
                            Ulice = "Družstevní"
                        },
                        new
                        {
                            Id = 4,
                            Email = "novotny@web.cz",
                            Heslo = "test",
                            Jmeno = "Petr",
                            Prijmeni = "Novotný",
                            Telefon = "300 600 500",
                            TypId = 3
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DatumOdeslani")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("DatumOdeslani"));

                    b.Property<string>("DestinaceCP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceMesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinacePsc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinaceUlice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KuryrId")
                        .HasColumnType("int");

                    b.Property<int>("OdesilatelId")
                        .HasColumnType("int");

                    b.Property<int>("PrijemceId")
                        .HasColumnType("int");

                    b.Property<int>("StavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KuryrId");

                    b.HasIndex("OdesilatelId");

                    b.HasIndex("PrijemceId");

                    b.HasIndex("StavId");

                    b.ToTable("Zasilka");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = "532-65-33",
                            DatumOdeslani = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinaceCP = "4653",
                            DestinaceMesto = "Zlín",
                            DestinacePsc = "760 01",
                            DestinaceUlice = "Kvítková",
                            KuryrId = 4,
                            OdesilatelId = 3,
                            PrijemceId = 2,
                            StavId = 2
                        });
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.HasOne("DorucovaciSluzba.Domain.Entities.TypUzivatel", "Typ")
                        .WithMany()
                        .HasForeignKey("TypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Typ");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Zasilka", b =>
                {
                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Kuryr")
                        .WithMany()
                        .HasForeignKey("KuryrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Odesilatel")
                        .WithMany("OdeslaneZasilky")
                        .HasForeignKey("OdesilatelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.Uzivatel", "Prijemce")
                        .WithMany("PrijateZasilky")
                        .HasForeignKey("PrijemceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DorucovaciSluzba.Domain.Entities.StavZasilka", "Stav")
                        .WithMany()
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kuryr");

                    b.Navigation("Odesilatel");

                    b.Navigation("Prijemce");

                    b.Navigation("Stav");
                });

            modelBuilder.Entity("DorucovaciSluzba.Domain.Entities.Uzivatel", b =>
                {
                    b.Navigation("OdeslaneZasilky");

                    b.Navigation("PrijateZasilky");
                });
#pragma warning restore 612, 618
        }
    }
}
